name: mcctf
version: 3.5.0
description: The classic MCPVP plugin reborn
author: NomNuggetNom
main: com.mcpvp.battle.BattlePlugin
depend: []
permissions:
  mcctf.flag.jump:
    description: Allow access to /flag jump
    default: op
  mcctf.flag.lock:
    description: Allow access to /flag lock
    default: op
  mcctf.flag.unlock:
    description: Allow access to /flag unlock
    default: op
  mcctf.flag.reset:
    description: Allow access to /flag reset
    default: op
  mcctf.flag.type:
    description: Allow access to /flag type
    default: op
  mcctf.flag.display:
    description: Allow access to /flag display
    default: true

  mcctf.kit:
    description: Allow access to /kit <class>
    default: true

  mcctf.kits.disable:
    description: Allow access to /kits disable
    default: op
  mcctf.kits.enable:
    description: Allow access to /kits enable
    default: op
  mcctf.kits.limit:
    description: Allow access to /kits limit <set|remove>
    default: op
  mcctf.kits.summary:
    description: Allow access to /kits summary
    default: true

  mcctf.respawn:
    description: Allows access to /respawn
    default: true

  mcctf.map.override:
    description: Allow access to /map override
    default: op
  mcctf.map.next:
    description: Allow access to /map next
    default: op
  mcctf.map.info:
    description: Allow access to /map info
    default: true
  mcctf.map.search:
    description: Allow access to /map search
    default: true

  mcctf.timer.set:
    description: Allow access to /timer set
    default: op
  mcctf.timer.lock:
    description: Allow access to /timer lock
    default: op
  mcctf.timer.unlock:
    description: Allow access to /timer unlock
    default: op
  mcctf.timer.skip:
    description: Allow access to /timer skip
    default: op

  mcctf.yell:
    description: Allow access to /yell
    default: true

  mcctf.switch:
    description: Allow access to SELF /switch
    default: true
  mcctf.switch.other:
    description: Allow switching the team of other players
    default: op
commands:
  captures:
    description: Capture management commands
  captures set:
    description: Set the number of captures for a team
    usage: /<command> <team> <number>
    permission: mcctf.captures.set
  flag:
    description: Flag commands
  flag jump:
    description: Jump to a flag
    usage: /<command> <team>
    permission: mcctf.flag.jump
  flag lock:
    description: Lock a flag to prevent it from being stolen
    usage: /<command> <team>
    permission: mcctf.flag.lock
  flag unlock:
    description: Unlock a flag to allow it to be stolen
    usage: /<command> <team>
    permission: mcctf.flag.unlock
  flag reset:
    description: Reset a flag to its normal state
    usage: /<command> <team>
    permission: mcctf.flag.reset
  flag display:
    description: Control which channels flag alerts are visible on
    usage: /<command> <chat | subtitle | actionbar> <on | off>
    permission: mcctf.flag.display
  flag type:
    description: Change the flag type
    usage: /<command> <wool | banner>
    permission: mcctf.flag.type
  kit:
    description: Select a class
    usage: /<command> <class | random>
    aliases: [class, archer, assassin, chemist, dwarf, elf, engineer, heavy, mage, medic, necro, ninja, pyro, scout, soldier, thief, vampire, mage2, random, classe, arqueiro, assassino, quimico, químico, anao, anão, elfo, engenheiro, guerreiro, mago, medico, médico, incendiario, incendiário, batedor, soldado, ladrao, ladrão, vampiro, mago2, aleatorio]
  kits:
    description: Manage the classes, such as disabling and setting limits
    aliases: [classes, classmanager]
  kits summary:
    description: View current class controls
    usage: /<command>
    permission: mcctf.kits.summary
  kits disable:
    description: Disable a class so that no players can use it
    usage: /<command> <class>
    permission: mcctf.kits.disable
  kits enable:
    description: Enable a class so that players can use it
    usage: /<command> <class>
    permission: mcctf.kits.enable
  kits limit:
    description: Manage kit limits
    usage: /<command> <set | remove>
  kits limit set:
    description: Limit a class so that only a certain number of players can use it
    usage: /<command> <class | all> <limit>
    permission: mcctf.kits.limit
  kits limit remove:
    description: Remove a class limit so that anyone can use it
    usage: /<command> <class | all>
    permission: mcctf.kits.limit
  map:
    description: Manage maps
  map info:
    description: View the current map
    usage: /<command>
    permission: mcctf.map.info
  map override:
    description: Specify maps to be played on reboot
    usage: /<command> <map ids>
    permission: mcctf.map.override
  map next:
    description: Insert a new game with the given map after the current game
    usage: /<command> <map ids>
    permission: mcctf.map.next
  map search:
    description: Search enabled maps by name
    usage: /
    permission: mcctf.map.search
  respawn:
    description: Respawn yourself immediately
    usage: /<command>
    permission: mcctf.respawn
  switch:
    description: Switch to the other team
    usage: /<command>
    permission: mcctf.switch
  timer:
    description: Manage the game timer
  timer set:
    description: Set the current time (in seconds) left on the timer
    usage: /<command> <seconds>
    permission: mcctf.timer.set
  timer lock:
    description: Lock the timer to prevent it from counting down
    permission: mcctf.timer.lock
  timer unlock:
    description: Unlock the timer to allow it to begin counting down
    permission: mcctf.timer.unlock
  timer skip:
    description: Advance the game as if the timer has immediately expired
    permission: mcctf.timer.skip
  yell:
    description: Yell!
    aliases: [a, all, g]
    permission: mcctf.yell
